version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 536460581283.dkr.ecr.eu-west-1.amazonaws.com
      - REPOSITORY_URI=536460581283.dkr.ecr.eu-west-1.amazonaws.com/try
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - docker pull docker184id/test:latest
      - docker tag docker184id/test:latest 536460581283.dkr.ecr.eu-west-1.amazonaws.com/try:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 536460581283.dkr.ecr.eu-west-1.amazonaws.com/try:latest
      - printf '[{"name":"tomcat-webserver","imageUri":"%s"}]' 536460581283.dkr.ecr.eu-west-1.amazonaws.com/try:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
