version: "3"
services:
  task:
    image: task
    ports:
      - "6060:8080"
    networks:
      - employee-mysql
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    networks:
      - employee-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lavagna 
    volumes:
      - myapp:/home/app
volumes:
  myapp: 

networks:
  employee-mysql: 
